### ISSUE TITLE
self.process.EnumToken - TypeError

### ISSUE THREAD

**Issue by ssmithTaylor** [XanaDublaKublaConch/pysdtoken#1]
I'm receiving a TypeError (byref() argument must be a ctypes instance, not '_ctypes.PyCArrayType') when self.process.EnumToken executes.

The exception appears to be triggered by the byref(lpTokens) arg.

Code is current version cloned from repo, execution environment is OSX Mojave. Python version is 3.7.2.

I have 0 experience with C type languages, to this error is throwing me for a loop.

Update:

I tested on Windows 10 as well with the 64bit client v5.0.2 and I'm getting the same result.

**Comment by XanaDublaKublaConch** [comment]
I'll see if I can figure it out. My only testable machine is my work PC (Win 10, Python 3.7.x 32-bit), so I'll have to wait until I get back and have a few cycles. The lpTokens arg is supposed to be an array of tokeninfo structs. A lot of what I did here is based on limited knowledge and lucky guesses/trial-and-error, so it works on my machine, but you're the second person telling me they're running into errors. It would be nice if RSA offered a dev installation, but I haven't found one. I'll keep you posted.

**Comment by ssmithTaylor** [comment]
@XanaDublaKublaConch

Thanks, I've been poking at it but not a lot of luck.

To some extent it's testable with just the client installed. For the windows test I got the binary from their forums and just bypassed the registered tokens check.

**Comment by XanaDublaKublaConch** [comment]
Yeah. I guess the basic calls should still work, but it will return 0 tokens. I'll give it a shot on my home machine.

**Comment by XanaDublaKublaConch** [comment]
Home PC (Win 10, Python 3.7.x, 32-bit) RSASecurIDSoftwareToken5.0.2x64 (with automation):
$ py
Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:06:47) [MSC v.1914 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pysdtoken
>>> sd = pysdtoken.SDProcess()
Qt: Untested Windows version 10.0 detected!
DEBUG: Token service started, handle 2.
DEBUG: There are 0 tokens.
There are no registered tokens.
>>>
It seems to work on my home machine, which is similar to my work machine, except for the 64-bit soft token. I don't have any way to import an actual token, tho.

**Comment by ssmithTaylor** [comment]
I'm thinking the issue is the 64 bit client, unfortunately it's the only option on Mac.

**Comment by ssmithTaylor** [comment]
With a few changes I was able to get it mostly working on mac. It seems like the changes are compatible with both, you'd just need to know how to find the dll.

Token retrieval does _partially_ work, unfortunately it doesn't seem to work as expected when you _do_ have a PIN. The behavior I'm currently seeing is I pass in the pin, retrieved token is equivalent to if pin was entered as null. I'm not sure why it seems to be acting as though I'm not passing a pin at all. I have confirmed it's being passed in GetCurrentCode.

Here are my modifications to your version,

```
"""
Provide python access to th eRSA Soft Token Service
This module wraps the stauto32.dll calls using
ctypes to get the current code from the token
"""

from ctypes import *

LONG = c_long // Don't have WIN methods on Mac, c_long seems to work the same.

# A struct to hold token error information
class struct_tagTOKENERRORINFO(Structure):
    _pack_ = 1  # source:False
    _fields_ = [
        ('error', c_int32),
        ('error_string', c_char * 24),
        ('detailed_error_string', c_char * 64)
    ]


token_error_info = struct_tagTOKENERRORINFO


# A struct to hold token information
class struct_tagTOKENBASICINFO(Structure):
    _pack_ = 1  # source:False
    _fields_ = [
        ('dwSize', c_long),
        ('serialnumber', c_char * 24),
        ('username', c_char * 24),
        ('deviceID', c_char * 24),
        ('descriptor', c_char * 64)
    ]


token_basic_info = struct_tagTOKENBASICINFO


# A struct to hold dates
class struct_CK_DATE(Structure):
    _pack_ = 1  # source:False
    _fields_ = [
        ('year', c_ubyte * 4),
        ('month', c_ubyte * 2),
        ('day', c_ubyte * 2)
    ]


CKDATE = struct_CK_DATE


class Token():
    """
    Token object to hold token info and function calls
    """

    def __init__(self, token_data):
        # Take a dict and parse it out
        self.serialnumber = token_data['serialnumber']
        self.username = token_data['username']
        self.deviceID = token_data['deviceID']
        self.descriptor = token_data['descriptor']
        self.is_default = token_data['is_default']

    def get_expiration_dat(self, token_service):
        return token_service.get_token_expiration_date(self.serialnumber)

    def get_current_code(self, token_service, pin=''):
        return token_service.get_token_current_code(self.serialnumber, pin)

class SDProcess():

    tokens = []
    lTokens = LONG()

    def __init__(self):
        # Get the SD process
        try:
            self.process = cdll.LoadLibrary('/Library/Frameworks/stauto32.framework/Versions/Current/stauto32') // Updated to cdll.LoadLibrary, seems to be compatible with both systems.
        except Exception as e:
            print(e)
            print("Error finding Soft Token service.")

        self.handle = LONG()
        self.lDefaultToken = LONG()
        self.open_service()
        # Populate lTokens and dwBuffersize
        self.dwBuffersize = self.count_tokens()
        print("DEBUG: There are {} tokens.".format(self.lTokens.value))
        # Populate the token dict
        self.tokens = self.get_tokens()
        print(self.tokens)

    def open_service(self):
        try:
            # > 0 means success and dwBuffersize is set
            if self.process.OpenTokenService(byref(self.handle)) > 0:
                print("DEBUG: Token service started, handle {}.".format(self.handle.value))
            else:
                print("No token service found!")
        except Exception as e:
            print(e)
            print("Error opening token service.")

    def close_service(self):
        try:
            # > 0 means success
            if self.process.CloseTokenService(self.handle) > 0: //Wasn't working with the byref in front of self.handle
                print("DEBUG: Token Service closed")
            else:
                print("Could not close token service.")
        except Exception as e:
            print(e)
            print("Error closing service.")

    def count_tokens(self):
        # See if there are any registered tokens and set up the buffer
        dwBuffersize = LONG()
        try:
            # lTokens gets filled with the token count. Don't provide a token array pointer yet
            # Send 0 the first time in case there are no tokens to grab
            self.process.EnumToken(self.handle, byref(self.lTokens), byref(self.lDefaultToken), 0, byref(dwBuffersize))
        except Exception as e:
            print(e)
            print("Error getting number of tokens.")
            return ''

        # if we got here, we didn't receive an error from the token service. The token count
        # is now stored in lTokens as a LONG
        if self.lTokens.value > 0:
            return dwBuffersize
        else:
            return ''

    def get_tokens(self):
        # Get the number of tokens registered with the token service by enumerating. The lTokens
        # var gets filled with a count. lDefaultToken gets filled with the index of the system
        # default token in the returned array

        # First, see if there are any registered tokens. If not, return an empty dict
        if self.lTokens.value == 0:
            print("There are no registered tokens.")
            return {}

        # Create an array of token structs
        lpTokens = (token_basic_info * self.lTokens.value)() //Resolves the issue I was having with byref in EnumToken
        tokens = []

        # There are lTokens # of tokens. Get them in an array. The dwBuffersize has to have been set
        # previously, which is done during init in the count_tokens() call. If dwBuffer points to a
        # null DWORD, the function will return zero/false and fill dwBuffersize withthe correct size
        try:
            if self.process.EnumToken(self.handle, byref(self.lTokens), byref(self.lDefaultToken), lpTokens,
                                      byref(self.dwBuffersize)) > 0: //lpTokens seems to work fine as shown
                print("{} tokens found:".format(self.lTokens.value))
            else:
                print("Did not find any tokens.")

        except Exception as e:
            print(e)
            print("Error getting tokens.")
            return []

        # Grab the token basic info for each token into a Token array. All stauto32 strings are utf-8
        for x, token in enumerate(lpTokens): //Changed to a dict and added .update, previous method didn't seem to work for me
            token_data = {}
            token_data.update({'serialnumber': token.serialnumber.decode('utf-8')})
            token_data.update({'username': token.username.decode('utf-8')})
            token_data.update({'deviceID': token.deviceID})
            token_data.update({'descriptor': token.descriptor})
            if self.lDefaultToken.value == x:
                token_data.update({'is_default': True})
            else:
                token_data.update({'is_default': False})
            tokens.append(Token(token_data))
        return tokens

    def get_default_token(self):
        if self.lTokens.value > 0:
            return self.tokens[self.lDefaultToken.value]
        else:
            return None

    def get_token_current_code(self, serial, pin):
        # get the current code that would be displayed on the token screen
        # return a tuple of code + time-left
        chPASSCODE = c_char_p("".encode("utf-8"))
        chPRN = c_char_p("".encode("utf-8"))
        lTimeLeft = LONG()

        try:
            self.process.GetCurrentCode(self.handle, serial.encode("utf-8"), pin.encode('utf-8'),
                                        byref(lTimeLeft), chPASSCODE, chPRN) // added .encode('utf-8) to pin, wasn't working without it.
        except Exception as e:
            print(e)
            print("Error getting token code.")
        # On pinless tokens, PASSCODE and PRN will be the same
        return (chPASSCODE.value.decode('utf-8'), chPRN.value.decode('utf-8'), lTimeLeft.value)

    def get_token_expiration_date(self, serial):
        # Get the expiration date of the token with this serial number
        # The date is returned as a CKDATE struct
        eDate = CKDATE()

        # Get the struct and parse it - Should I use datetime library here instead of a string?
        try:
            # > 0 means success
            if self.process.GetTokenExpiration(self.handle, serial.encode('utf-8'), byref(eDate)) > 0:
                token_expiration = "{0}/{1}/{2}".format(bytes(eDate.month).decode('utf-8'),
                                                        bytes(eDate.day).decode('utf-8'),
                                                        bytes(eDate.year).decode('utf-8')
                                                        )
            else:
                token_expiration = None
        except Exception as e:
            print(e)
            print("Error getting token expiration date.")
            token_expiration = None

        return token_expiration
```

**Comment by XanaDublaKublaConch** [comment]
Thanks. I'll check out those changes and wrap them in. I'm not sure why it won't take the pin. Here's the parameter info from the SDK:

[in] | pPin | Pointer to a constant null-terminated string that contains the PIN to be  used for generating the passcode. If this parameter is set to NULL, an empty  string, or four zeros (i.e. "0000"), pPasscode will return a tokencode (PRN)  instead.

I'll check my code and make sure my logic is good. The dll may be getting a null or empty string for some reason. I don't have a token with a PIN, so it's impossible for me to test it.

**Comment by ssmithTaylor** [comment]
Yeah, the pin issue is pretty confusing. I was hoping I'd find someone else posting about it online, but didn't have much luck.

It does seem to actually do some checking on the pin that's passed, so it is getting it and doesn't just ignore it. If I pass less than 3 chars, or alphabetic chars it doesn't generate a token at all. However if I do pass one of valid format/type, it always produces the same result as if I hadn't passed one at all.

Looking at the header, serial and pin are supposed to both be passed as the same type. Given the serial lookup is working with serial.encode('utf-8') that'd suggest it's not a type issue. I guess it's possible it's expecting something other than bytes, but the header file hasn't been helpful in determining what.

Aside from the token generation issue I'm only seeing one remaining problem on mac. For some reason close_service takes several seconds to run. If I skip close_service, total execution time to get a token is .4s, with close_service I'm looking at 2.8s. Ending the script without closing the service causes a segfault, so it's not viable to just skip it.

This slowness issue doesn't appear to impact windows, though it's not an apples to apples (ha) comparison since I don't have a real token on windows.

I (personally) see two benefits to interfacing with SecurID via this method. One is speed, the other is accuracy/reliability.

Unfortunately while the close_service issue remains this method is at least 2x slower than just emulating keyboard input. The only remaining benefit would be better reliability, but I value speed above that to a reasonable degree.

-------

All that being said, I really like the project and am excited to see where it goes. Hopefully someone else with more experience in this area than me will come along and be able to resolve some of these problems.

**Comment by XanaDublaKublaConch** [comment]
I was playing around last night and added a wrap for the token error call from the dll. You can try checking for token errors after passing the pin by adding this function to the SDProcess class:
```python
    def get_token_error(self):
        # Get any error info in the token
        # Create a TOKENERRORINFO struct
        token_error = token_error_info()
        # get a pointer to the struct
        lp_token_error = pointer(token_error)
        # Call the dll function, passing in the struct pointer to get filled. > 0 is success
        if self.process.GetTokenError(self.handle, lp_token_error) > 0:
            if lp_token_error is not None and token_error is not None:
                # Dereference the pointer/get contents of fields
                content = lp_token_error.contents
                print("Error #: {}".format(content.error))
                print("Description: {}".format(content.error_string.decode('utf-8')))
                print("Details: {}".format(content.detailed_error_string.decode('utf-8')))
            else:
                print("Returned NULL pointer")
        else:
            print("No token errors.")

**Comment by ssmithTaylor** [comment]
I'll try that, it returns a status code 1 so I'm not sure there will be one.

**Comment by ssmithTaylor** [comment]
I get an error 17, regardless of where I'm the process I call the get error function.

Edit: Not true, I've tested in a few more places and made some fixes. I haven't been able to resolve part yet, after setting dwbuffersize I also see the error 17.

I'll poke it more when I get home.

**Comment by XanaDublaKublaConch** [comment]
According to the header file in the SDK, 17 is buffer too small. The function always returns the last token error, so even if no new errors are generated, you'll still get the last one that was generated. I've made some updates on my home version and created a TokenError enum to plug into the get error function so it returns better results. I'll upload my changes today. I also HAVE to use windll on my system, so I do a platform check in the SDProcess init and use windll on windows systems and cdll on others. c_long still seems to work, so I don't need wintypes.

I also spent some time with stoken last night trying to generate a fake token, but the sdtids it issues just crash my soft token at home. :(

**Comment by XanaDublaKublaConch** [comment]
I was able to create a fake token with a pin using stoken.

Tons of debugging print statements later, it turns out that ctypes was setting chPASSCODE and chPIN to the same pointer. Instead of initializing them both with '', I changed it to:
```python
        chPASSCODE = c_char_p("one".encode("utf-8"))
        chPRN = c_char_p("two".encode("utf-8"))
```

and it worked.

```
>>> tk.get_current_code(sd, '12345678')
Calling with c_long(2), b'000408697973', c_char_p(58552720), <cparam 'P' (03833198)>, c_char_p(58698200). c_char_p(58921128)
('89636651', '77391083', 17)

**Comment by ssmithTaylor** [comment]
Nice work! I'll give it a shot. 

Update: 

Looks good. Can you provide the updated error lookup too? I'm hoping it'll be possible to figure out the elongated service close time.

**Comment by XanaDublaKublaConch** [comment]
Yep. Did the other bit on my lunch break. I'll update the rest tonight. I also need to update the process init. I have to use windll to load or all of the calls fail, so I have a platform-specific load on my copy.

**Comment by ssmithTaylor** [comment]
New observation on the slow close issue.

If I add a breakpoint right before the call to close token service and wait to proceed a few seconds when I actually execute the call it goes through quickly.

Seems like something may be going on that finishes after a few seconds and holds the service open.

**Comment by XanaDublaKublaConch** [comment]
I pushed the update after an hour on the struggle-bus. I need to learn how to use pycharm and github together correctly. :) Let me know if it breaks anything on the mac side.

**Comment by ssmithTaylor** [comment]
New version seems to work fine on Mac

**Comment by ssmithTaylor** [comment]
I'd say this one's resolved, I'll open new issues for anything else. Should have added the resolve tag to my commit, oh well.
