### ISSUE TITLE
Remove Print Statments from pysdtoken

### ISSUE THREAD

**Issue by ssmithTaylor** [XanaDublaKublaConch/pysdtoken#7]
In order to better serve its function as a library loaded by other scripts I believe it would be best to reduce the verbosity of pysdtoken.

In my opinion, the best way to do this would be to use the logging module and replace the existing error and debug print statements with the equivalent library call.

I'm not sure if you're already doing this, but I would be happy to do so myself as well.

My current thought is to set a global log level at the module level and add a kwarg to SDProcess __init__ to allow overriding it if the caller wants something more verbose.

**Comment by XanaDublaKublaConch** [comment]
It was on my to-do list, but you are welcome to tackle it if you have cycles. I've only done a little bit with that module when I was working with Selenium, so if you have some experience with it, I'm all for it.
